# ----------------------------------------
# SERVER CONFIGURATION
# ----------------------------------------
server.port=8082

# ----------------------------------------
# EMAIL / SMTP CONFIGURATION (MAILTRAP)
# ----------------------------------------
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525

spring.mail.username=064c2747f8932f
spring.mail.password=0c183096e791c9

# SMTP Protocol settings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
